version: "3.6"
services:
  backend:
    image: ghcr.io/it-cheat-sheet/back-end-nodejs:latest
    container_name: backend
    ports:
       - "3000:3000"

networks:
    default:
        external:
            name: it-cheatsheet-network
