name: Back-end

on:
  push:
    branches: 
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout code
      uses: actions/checkout@v2

      
    - name: Login to Github registry ghcr
      uses: docker/login-action@v1
      with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.ITCHEATSHEET_TOKEN }}
         
    - name: Create env file
      run: |
          touch .env
          echo MYSQL_URL=${{ secrets.MYSQL_URL }} >> .env
         
    - name: Build docker image
      run: docker build . --file Dockerfile --tag ghcr.io/it-cheat-sheet/back-end-nodejs:latest 
      
    - name: Push docker image to registry
      run: |
         docker push ghcr.io/it-cheat-sheet/back-end-nodejs:latest
   
    - name: Publish compose file
      uses: appleboy/scp-action@master
      with: 
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         source: ./docker-compose.dev.yml
         target: ./backend
    
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
           docker-compose -f backend/docker-compose.dev.yml down 
           docker pull ghcr.io/it-cheat-sheet/back-end-nodejs:dev
           docker-compose -f backend/docker-compose.dev.yml up -d 
